#!/bin/bash

# List files in the current directory
echo "Current Directory:"
ls -la

# List files in the parent directory
echo "Parent Directory:"
ls -la ..

# List files in the /boot directory
echo "/boot Directory:"
ls -la /boot

